In [1]:
import pandas as pd

Total number of files in the dataset

In [19]:
!ls --almost-all -o ../data | wc -l

3362

In [8]:
df = pd.read_csv('../data/-0.0332440668675476_-75.45230903823258.csv', delimiter=';')
df.head()

,lang,id,created_at,text,conversation_id,in_reply_to_user_id,reply_settings,source,possibly_sensitive,geo_place_id,...,author_protected,author_description,retweet_count,reply_count,like_count,quote_count,followers_count,following_count,tweet_count,listed_count
0,es,1432423525642551297,2021-08-30T19:22:36.000Z,"@Mafercoronelq Ese mal hay en todo el país, sa...",1432422579873239045,1.593809e+09,everyone,Twitter for Android,False,005913f135015c2c,...,False,Agradecido con Dios por tener a mis padres.. H...,0,0,0,0,56,541,1034,0
1,es,1431420873018380293,2021-08-28T00:58:25.000Z,En ceremonia realizada bajo todos los protocol...,1431420873018380293,NaN,everyone,Twitter for iPhone,False,005ea8645e852498,...,False,Cuenta Oficial de la Fuerza Naval del Sur. Uni...,0,0,1,0,406,59,601,3
2,es,1431309098021269517,2021-08-27T17:34:16.000Z,"Con una ceremonia, eucaristía y recorrido por ...",1431309098021269517,NaN,everyone,Twitter for iPhone,False,005ea8645e852498,...,False,Cuenta Oficial de la Fuerza Naval del Sur. Uni...,3,0,6,0,406,59,601,3
3,es,1430947724824825857,2021-08-26T17:38:17.000Z,En el muelle principal de la #FlotillaFluvialD...,1430947724824825857,NaN,everyone,Twitter for iPhone,False,005ea8645e852498,...,False,Cuenta Oficial de la Fuerza Naval del Sur. Uni...,1,0,2,0,406,59,601,3
4,es,1430332319513026561,2021-08-25T00:52:53.000Z,Qué hijueputa falta me hace visitar una librería.,1430332319513026561,NaN,everyone,Twitter for Android,False,005ea8645e852498,...,False,"Ecléctico, ansioso y contradictorio. Maestro r...",0,0,0,0,160,550,1633,2